### ISSUE TITLE
submenu open in the left side of parent, possible?

### ISSUE THREAD

**Issue by RodrigoZanotta** [fontenele/bootstrap-navbar-dropdowns#11]
i have a submenu that stars right on the edge of the screen, so i can't see it when i hover. is it possible to make the submenu open in the left side of the parent?
![edge](https://user-images.githubusercontent.com/976964/36322362-28c1b728-1334-11e8-893d-09bfbb554904.png)

**Comment by fontenele** [comment]
Hi @RodrigoZanotta 
can you test it? I changed de example.html, added a right navbar menu with submenus.
