### ISSUE TITLE
2nd and 3rd level links don't open target pages in FF & Chrome for Mac

### ISSUE THREAD

**Issue by muizonline** [fontenele/bootstrap-navbar-dropdowns#16]
This Bootstrap v4 multi-level navbar is exactly what I've been looking for, and although the example.html demo works as described, when converting the demo into a real-world navbar (ie moving the 'href=' attributes out of the 'li' list item tags into the 'a' anchor tags where they need to be, and changing the default '#' values to valid URL values), none of the 2nd and 3rd level sub-menu links actually work. Clicking on them simply closes the menu, instead of loading the target pages. 

See my 'exampleLinks.html' file, attached.

Thanks, Muiz.

[exampleLinks.html.zip](https://github.com/fontenele/bootstrap-navbar-dropdowns/files/2611789/exampleLinks.html.zip)

**Comment by fontenele** [comment]
I understand your problem, i am working now to fix this for you.

**Comment by muizonline** [comment]
Thank you.

**Comment by muizonline** [comment]
Good luck with the troubleshooting!

**Comment by fontenele** [comment]
@muizonline @artlarson 

Please test the fix solution.

https://github.com/fontenele/bootstrap-navbar-dropdowns/commit/6f974b8188bc3e23644404b2799ed93c526d5df5
