### ISSUE TITLE
In Mobile device it's not working!!!!!

### ISSUE THREAD

**Issue by prashen** [fontenele/bootstrap-navbar-dropdowns#2]
Hi,
In desktop everything is fine but you give hover event in desktop which is nice for desktop.
In mobile there is no hover event that is why it's not working. The last level dropdown which is on hover display in desktop not working in mobile. Can you fix this.
Thanks

**Comment by optyler** [comment]
as the navbar opens on clicks events, this issue could be close in my opinion.

**Comment by fontenele** [comment]
@prashen can you try again?
please [see this screenshot in my android](https://github.com/fontenele/bootstrap-navbar-dropdowns/blob/master/README.md)
