### ISSUE TITLE
Bootstrap 5 version?

### ISSUE THREAD

**Issue by mother10** [fontenele/bootstrap-navbar-dropdowns#21]
Will there be a Bootstrap 5 version? And if so when?

 I know Bootstrap 5 is still in alpha yet, but it would be great if it was supported.
Maybe keep 2 versions, one for Bootstrap 4 and a new one for Bootstrap 5.

Thanks!

**Comment by fontenele** [comment]
Hi @mother10 , thanks for submit your issue!

We will add this option in release 5.0
#22

**Comment by fontenele** [comment]
@mother10 now we have a bs5 example!!!

https://github.com/fontenele/bootstrap-navbar-dropdowns/blob/master/example-bs5.html
