### ISSUE TITLE
Add theme option to plugin

### ISSUE THREAD

**Issue by fontenele** [fontenele/bootstrap-navbar-dropdowns#22]

**Comment by mother10** [comment]
Bootstrap 5 has a better theming option, see the Customize section in the Bootstrap 5 docs.
It works by compiling the Bootstrap scss files through nmp with sass, i do that myself.

The theming is in the _ variables file for now. But they will change that i think see issue **v5: Sass file structure idea #29451** on url
[https://github.com/twbs/bootstrap/pull/29451](url)

So maybe thats enough???

**Comment by fontenele** [comment]
The theme in this case is the bootstrap version to dealing with DOM structure, bootstrap events and css class names.
