### ISSUE TITLE
Change to narrow mode

### ISSUE THREAD

**Issue by gtbu** [fontenele/bootstrap-navbar-dropdowns#28]
The dropdowns of BT5 function (example and codepen) but if i shift the browser into narrow mode, the menu is open at first level (firefox and edge)  and the Hamburger is dead.... a 'solution' would be a mobile sidebar...but.. (the bt4 - version functions)

**Comment by fontenele** [comment]
Fixed.

Just added class .collapse to `.navbar-collapse` div, and the toggler configs at `.navbar-toggle` button. 

`data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false"`
