### ISSUE TITLE
Hover option, maybe?

### ISSUE THREAD

**Issue by cacacobra** [fontenele/bootstrap-navbar-dropdowns#6]
Is it possible to make menu work with hover?

Thanks!

**Comment by RodrigoZanotta** [comment]
But it does work with hover.

**Comment by fontenele** [comment]
Hi @cacacobra 

Just change
`$('.navbar a.dropdown-toggle').on('click', `
to
`$('.navbar a.dropdown-toggle').on('mouseover'`

**Comment by fontenele** [comment]
Add to roadmap
