### ISSUE TITLE
Bootstrap 4 support

### ISSUE THREAD

**Issue by emmerink** [fontenele/bootstrap-navbar-dropdowns#8]
Hi, are there any plans to add Twitter Bootstrap 4 support?

**Comment by fontenele** [comment]
Not yet. In this moment the current version of bootstrap 4 is v4.0.0-alpha.6. I will wait the RC version to make support.

**Comment by kanlukasz** [comment]
Hello, is support for bootstrap 4 now? Is working ok with 4 final ?

**Comment by fontenele** [comment]
I will create a branch to make it works.

**Comment by AshLingua** [comment]
hi, well done. nice clean & nested. I'm working on one for BS 4 and there are, well, one or two issues. I hope your upgrade is going well.

**Comment by fontenele** [comment]
Now featured! Thanks for your suggestion!
